### ISSUE TITLE
How to run faster ？

### ISSUE THREAD

**Issue by YaoXinZhi** [rockt/SETH#29]
I run the script with the following command line: 

`java -cp seth-1.3-Snapshot-jar-with-dependencies.jar seth.ner.wrapper.SETHNERAppMut "{sentence}"
`

But I have 33,787,634 sentences, and it is estimated that it will take two weeks to complete the labeling.

Is there any way to make the program run faster?

**Comment by Erechtheus** [comment]
Hi @YaoXinZhi , you have some options.

First, you could parallelise by calling SETH using different processes. I can process all of PubMed on my laptop within less then 12 hours on my local laptop (distributed over 4 CPU cores) 

Second, keep in mind that calling SETH for each sentence requires to start the JVM first. I would really not recommend invoking the JVM 33 Million times. It would be better to  write a custom Java script.

**Comment by Erechtheus** [comment]
In other words, the use of "seth.ner.wrapper.SETHNERAppMut" is not recommended for  (larger scale) production use.

**Comment by YaoXinZhi** [comment]
Thank you very much for your answer, I can run SETH quickly now.

**Comment by YaoXinZhi** [comment]
Hi@Erechtheus , would you mind sharing your SETH parallel code ? I want to run SETH quickly, but I find it difficult to parallel JAVA with Python (I am not familiar with JAVA)

**Comment by Erechtheus** [comment]
How do you call Seth at the moment? Still for each document separately? Or did you write some code to process several documents inside the same jvm?

**Comment by YaoXinZhi** [comment]
Still for each document separately. But this consumes computing resources very much, and there is no obvious speed-up. .

**Comment by Erechtheus** [comment]
If you call SETH for each document you need to instantiate the JVM for each document. This takes "a lot" of time. Execution is substantially faster if you process several documents inside of the same JVM.  I would recommend to process several documents inside of the same JVM.

**Comment by Erechtheus** [comment]
@YaoXinZhi maybe you could explain what you would like to process and your current set-up? As explained, I cannot recommend calling SETH for each document seperately.  You could try to use the REST Service as explained here (http://rockt.github.io/SETH/). But this does not allow entity linking to dbSNP.
