### ISSUE TITLE
Bug Report, wrong offset.

### ISSUE THREAD

**Issue by YaoXinZhi** [rockt/SETH#30]
Sentence Id:	1611
PMID:	8886002
Sentence:	Familial Alzheimer's disease-linked mutations at Val717 of amyloid precursor protein are specific for the increased secretion of A beta 42(43). In some pedigrees of familial Alzheimer's disease (FAD), three mutations of beta amyloid precursor protein (APP) have been found at the Val717 residue (to Ile, Phe, or Cly) and these mutations increase the secretion of A beta 42(43). To study the specificity of the effects of these mutations on APP processing, we transiently expressed APP genes with mutations of Val717 to Lys, Ser, Glu, or Cys in COS cells. The three familial AD-linked mutations increased the levels or ratios of A beta 42(43), whereas the secretion of A beta 40 was decreased. Other mutations irrelevant to FAD except Val717 to Lys had little effect on the ratio of A beta 42(43). Substitution to Lys decreased the secretion of A beta 42(43); substitution to Glu or Gly decreased the amount of intracellular C-terminal fragment produced by alpha-secretase, whereas it was increased by mutations to Phe, Cys, or Lys. However, the levels of secretion of soluble APP were constant, but a substitution to Glu reduced it. These results suggest a specific role of the Val717 residue in APP processing and, especially, in gamma-cleavage.
Familial Alzheimer's disease-linked mutations at Val717 of amyloid precursor protein are specific for the increased secretion of A beta 42(43). In some pedigrees of familial 
Completed loading of regular expressions: 768 loaded.
MutationMention [span=509-522, mutResidue=K, location=717, wtResidue=V, text=Val717 to Lys, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=734-747, mutResidue=K, location=717, wtResidue=V, text=Val717 to Lys, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=509-532, mutResidue=E, location=717, wtResidue=V, text=Val717 to Lys, Ser, Glu, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=509-527, mutResidue=S, location=717, wtResidue=V, text=Val717 to Lys, Ser, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=509-540, mutResidue=C, location=717, wtResidue=V, text=Val717 to Lys, Ser, Glu, or Cys, type=SUBSTITUTION, tool=MUTATIONFINDER]
Extracted 5 mutations.

In this labeling scenario, the labeled offset information does not match the actual text, for example:
tagging: ('Val717 to Lys', 'SUBSTITUTION', ('509', '532'))
tagging text: Val717 to Lys
actual text: Val717 to Lys, Ser, Glu

**Comment by Erechtheus** [comment]
Could you please elaborate more? 

If I invoke:
`java -cp target/seth-1.3.2-Snapshot-jar-with-dependencies.jar seth.ner.wrapper.SETHNERAppMut "Familial Alzheimer's disease-linked mutations at Val717 of amyloid precursor protein are specific for the increased secretion of A beta 42(43). In some pedigrees of familial Alzheimer's disease (FAD), three mutations of beta amyloid precursor protein (APP) have been found at the Val717 residue (to Ile, Phe, or Cly) and these mutations increase the secretion of A beta 42(43). To study the specificity of the effects of these mutations on APP processing, we transiently expressed APP genes with mutations of Val717 to Lys, Ser, Glu, or Cys in COS cells. The three familial AD-linked mutations increased the levels or ratios of A beta 42(43), whereas the secretion of A beta 40 was decreased. Other mutations irrelevant to FAD except Val717 to Lys had little effect on the ratio of A beta 42(43). Substitution to Lys decreased the secretion of A beta 42(43); substitution to Glu or Gly decreased the amount of intracellular C-terminal fragment produced by alpha-secretase, whereas it was increased by mutations to Phe, Cys, or Lys. However, the levels of secretion of soluble APP were constant, but a substitution to Glu reduced it. These results suggest a specific role of the Val717 residue in APP processing and, especially, in gamma-cleavage. Familial Alzheimer's disease-linked mutations at Val717 of amyloid precursor protein are specific for the increased secretion of A beta 42(43). In some pedigrees of familial"
Familial Alzheimer's disease-linked mutations at Val717 of amyloid precursor protein are specific for the increased secretion of A beta 42(43). In some pedigrees of familial Alzheimer's disease (FAD), three mutations of beta amyloid precursor protein (APP) have been found at the Val717 residue (to Ile, Phe, or Cly) and these mutations increase the secretion of A beta 42(43). To study the specificity of the effects of these mutations on APP processing, we transiently expressed APP genes with mutations of Val717 to Lys, Ser, Glu, or Cys in COS cells. The three familial AD-linked mutations increased the levels or ratios of A beta 42(43), whereas the secretion of A beta 40 was decreased. Other mutations irrelevant to FAD except Val717 to Lys had little effect on the ratio of A beta 42(43). Substitution to Lys decreased the secretion of A beta 42(43); substitution to Glu or Gly decreased the amount of intracellular C-terminal fragment produced by alpha-secretase, whereas it was increased by mutations to Phe, Cys, or Lys. However, the levels of secretion of soluble APP were constant, but a substitution to Glu reduced it. These results suggest a specific role of the Val717 residue in APP processing and, especially, in gamma-cleavage. Familial Alzheimer's disease-linked mutations at Val717 of amyloid precursor protein are specific for the increased secretion of A beta 42(43). In some pedigrees of familia"`


I get:
```
MutationMention [span=509-540, mutResidue=C, location=717, wtResidue=V, text=Val717 to Lys, Ser, Glu, or Cys, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=734-747, mutResidue=K, location=717, wtResidue=V, text=Val717 to Lys, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=509-522, mutResidue=K, location=717, wtResidue=V, text=Val717 to Lys, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=509-527, mutResidue=S, location=717, wtResidue=V, text=Val717 to Lys, Ser, type=SUBSTITUTION, tool=MUTATIONFINDER]
MutationMention [span=509-532, mutResidue=E, location=717, wtResidue=V, text=Val717 to Lys, Ser, Glu, type=SUBSTITUTION, tool=MUTATIONFINDER]
```

What is exactly wrong?

**Comment by YaoXinZhi** [comment]
Oh, I’m sorry, it seems that my own code parsing is wrong, thank you for your answer.
