### ISSUE TITLE
Error: cannot find or fail to load the main class de.hu.berlin.wbi.stuff.dbSNPParser.xml.ParseXMLToFile when Parse dbSNP-XML dump

### ISSUE THREAD

**Issue by pqq1999** [rockt/SETH#36]

**Comment by Erechtheus** [comment]
Please explain in more detail what you were trying to do. Did you use bash?

**Comment by pqq1999** [comment]
I followed the readme “https://rockt.github.io/SETH/” to Parse dbSNP-XML file，but failed.
the command line is "java -cp seth.jar -Djdk.xml.totalEntitySizeLimit=0 -DentityExpansionLimit=0 de.hu.berlin.wbi.stuff.dbSNPParser.xml.ParseXMLToFile"

**Comment by Erechtheus** [comment]
Unable to reproduce. 

```
git clone https://github.com/rockt/SETH.git
cd SETH
mvn clean compile assembly:single
mv ./target/seth-1.3.2-Snapshot-jar-with-dependencies.jar seth.jar
java -cp seth.jar -Djdk.xml.totalEntitySizeLimit=0 -DentityExpansionLimit=0 de.hu.berlin.wbi.stuff.dbSNPParser.xml.ParseXMLToFile

```

works for me

**Comment by pqq1999** [comment]
thanks for your instruction, but it still failed to work. After adding "import de.hu.berlin.wbi.stuff.dbSNPParser.xml.*;" in the SETH.java, it works successfully.    from Qianqian Peng(HZAU BioNLP Lab)
